// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2GyAaB-aWDJulilbgE0mji7e0EiPbSCI',
    appId: '1:129767293539:web:8b543561d1713607536e56',
    messagingSenderId: '129767293539',
    projectId: 'auth-secondary-example',
    authDomain: 'auth-secondary-example.firebaseapp.com',
    storageBucket: 'auth-secondary-example.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT8xLyDS9gjQ5oPY9tqFd_dH3XY9Bl26A',
    appId: '1:129767293539:android:473106c086a1a86d536e56',
    messagingSenderId: '129767293539',
    projectId: 'auth-secondary-example',
    storageBucket: 'auth-secondary-example.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8qaUe7j0FPp1k59FOo7kBbdT7llSBXg4',
    appId: '1:129767293539:ios:1cb1352b1826f580536e56',
    messagingSenderId: '129767293539',
    projectId: 'auth-secondary-example',
    storageBucket: 'auth-secondary-example.firebasestorage.app',
    androidClientId: '129767293539-u83p4tfqqk6vp34ieebit2q7661cu1im.apps.googleusercontent.com',
    iosClientId: '129767293539-k9lqmrgm6o7k22d7mn8i54ebecuq8t0q.apps.googleusercontent.com',
    iosBundleId: 'com.busegorcum.signinSignup10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8qaUe7j0FPp1k59FOo7kBbdT7llSBXg4',
    appId: '1:129767293539:ios:1cb1352b1826f580536e56',
    messagingSenderId: '129767293539',
    projectId: 'auth-secondary-example',
    storageBucket: 'auth-secondary-example.firebasestorage.app',
    androidClientId: '129767293539-u83p4tfqqk6vp34ieebit2q7661cu1im.apps.googleusercontent.com',
    iosClientId: '129767293539-k9lqmrgm6o7k22d7mn8i54ebecuq8t0q.apps.googleusercontent.com',
    iosBundleId: 'com.busegorcum.signinSignup10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2GyAaB-aWDJulilbgE0mji7e0EiPbSCI',
    appId: '1:129767293539:web:ea4d7fca455ead3f536e56',
    messagingSenderId: '129767293539',
    projectId: 'auth-secondary-example',
    authDomain: 'auth-secondary-example.firebaseapp.com',
    storageBucket: 'auth-secondary-example.firebasestorage.app',
  );

}